---
version: '3'
services:

  agent:
    image: bcgovimages/aries-cloudagent:py3.9-indy-1.16.0_0.12.0rc2
    ports:
      - 8020:8020
    entrypoint: ["aca-py", "start"]
    command: [
      '--no-ledger',
      '--admin', '0.0.0.0', '8020',
      '--admin-insecure-mode',
      '--endpoint', 'http://agent:8021',
      '--outbound-transport', 'http',
      '--inbound-transport', 'http', '0.0.0.0', '8021'
    ]

  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  traceability-api:
    image: patstlouis91/traceability-controller:interop-0.0.1
    # build:
    #   context: ./traceability-controller
    ports:
      - 8000:8000
    entrypoint: ["python", "main.py"]
    environment:
      POSTGRES_URI: ${POSTGRES_URI}
      TRACTION_API_KEY: ${TRACTION_API_KEY}
      TRACTION_TENANT_ID: ${TRACTION_TENANT_ID}
      TRACTION_API_ENDPOINT: ${TRACTION_API_ENDPOINT}
      VERIFIER_ENDPOINT: ${VERIFIER_ENDPOINT}
      TRACEABILITY_CONTROLLER_DOMAIN: ${TRACEABILITY_CONTROLLER_DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.traceability-api.rule=Host(`${TRACEABILITY_CONTROLLER_DOMAIN}`)
      - traefik.http.routers.traceability-api.entrypoints=websecure
      - traefik.http.routers.traceability-api.tls.certresolver=myresolver
      - traefik.http.services.traceability-api.loadbalancer.server.port=8000

  traefik:
    image: traefik:v2.10
    restart: always
    security_opt:
      - no-new-privileges:true
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - 443:443
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  postgres_data:
  letsencrypt:
