---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "acapy.fullname" . }}-ingress
  labels:
    {{- include "acapy.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "acapy.selectorLabels" . | nindent 6 }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.ingress.namespaceSelector | nindent 14 }}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "acapy.fullname" . }}
  labels:
    {{- include "acapy.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "acapy.selectorLabels" . | nindent 6 }}
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.acapy.service.adminPort }}
      from:
        - podSelector:
            matchLabels:
              {{- include "controller.selectorLabels" . | nindent 14 }}
  policyTypes:
    - Ingress
